apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: latexservice-ingress
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  tls:
    - hosts:
        - "{{ .Values.hostname }}"
  rules:
    - host: "{{ .Values.hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: latexservice
                port:
                  number: 80
